### ISSUE TITLE
Criar o MER e o DER

### ISSUE THREAD

**Issue by lelamo2002** [fga-eps-mds/2022-2-Vambora#11]
# Modelagem diagrama do banco de dados

## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Levantar as tabelas iniciais | definir seus nomes e atributos |
|   02   | Organizar as tabelas listadas no modelo DER | Ter o diagrama feito|

- [x] Tarefa 01
- [x] Tarefa 02

## Responsáveis

| Assignees  |
| @SamuelRicardoDS |
| @lelamo2002  |

**Comment by SamuelRicardoDS** [comment]
DER feito pelo lucidchart, segue link do arquivo pelo lucid (pdf do diagrama criado, com possibilidade de atualizações constantes): https://lucid.app/lucidchart/676858c6-607c-4535-9a4b-c8a85e3edbea/edit?viewport_loc=-1029%2C-405%2C3687%2C1795%2C0_0&invitationId=inv_bf684fad-b197-4560-8c5f-5dd5224a1108
