### ISSUE TITLE
Back-end: Diagrama de relações (MER e DER)

### ISSUE THREAD

**Issue by julio-dourado** [fga-eps-mds/2022-2-Vambora#15]
# Back-end: Diagrama de relações (MER e DER)
## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Dividir tarefas entre a equipe | Divisão revisada |
|   02   |  Fazer Diagrama de Relações | Diagrama de Relações revisado |
|   03   | Documentar Diagrama de Relações | X |

- [x] Tarefa 01
- [x] Tarefa 02
- [x] Tarefa 03

**Comment by SamuelRicardoDS** [comment]
@lelamo2002 
MER e DER feitos pelo lucidchart e atualmente fidedignos a idealização do fluxo da aplicação. Assim, pode-se averiguar o diagrama de entidades de relacionamentos, bem como efetuar sua atualização a partir do seguinte link: https://lucid.app/lucidchart/676858c6-607c-4535-9a4b-c8a85e3edbea/edit?invitationId=inv_bf684fad-b197-4560-8c5f-5dd5224a1108&page=0_0#
