### ISSUE TITLE
Back-end: Documentação das rotas em Swagger

### ISSUE THREAD

**Issue by julio-dourado** [fga-eps-mds/2022-2-Vambora#17]
# Back-end: Documentação das rotas em Swagger

## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Documentar rota GET | Testes no Swagger. |
|   02   | Documentar rota POST | Testes no Swagger. |
|   03   | Documentar rota PUT | Testes no Swagger. |
|   04   | Documentar rota PATCH | Testes no Swagger. |
|   05   | Documentar rota DELETE | Testes no Swagger. |

- [x] Tarefa 01
- [x] Tarefa 02
- [x] Tarefa 03
- [x] Tarefa 04
- [x] Tarefa 05

## Responsáveis

| Assignees  |
| :--------: |
| @SamuelRicardoDS |
| @lelamo2002  |

**Comment by lelamo2002** [comment]
A documentação de todas as rotas foram feitas
