### ISSUE TITLE
Definição de Tema

### ISSUE THREAD

**Issue by gustavokenzo1** [fga-eps-mds/2022-2-Vambora#2]
Temos que definir uma proposta de projeto para o tema "Quais os problemas da unb/fga poderiam ser resolvidos por um software?".

Deadline: 03/11

Vamos tentar deixar a discussão registrada na issue ao invés do grupo do whatsapp.

Temas já discutidos pessoalmente:
1. Gerador de Grade Horária 
2. Formas de saber onde são as salas das matérias
3. Integrar com alguma API do RU uma forma de pagamento online

Conclusões sobre cada tema:
1. Já tenho um pronto, então todo o processo de estudo e conclusões acerca da coleta de dados, etc, já teria uma certa maturidade, e prejudicaria o desenvolvimento do grupo. Não resolve um problema frequente, pois ocorre apenas uma vez por semestre. 
2. Talvez não seja um problema tão grande no caso da FGA. Ainda não discutimos sobre formas de resolver esse problema por meio de software.
3. Evitaria as filas para colocar crédito. Teríamos que entrar em contato com a empresa que cuida do RU e pedir acesso ao banco de dados e a API deles, o que é um assunto extremamente delicado. Outra opção discutida seria implementar nosso próprio sistema do RU, com API de pagamento, porém isso não resolveria o problema, só simularia a resolução do problema, que para ter aplicação real dependeria da migração por parte da empresa terceirizada.

Comentem aqui em baixo sobre sugestões de temas e se faltou algum ponto além dos comentados acima.

@GustavoHenrique23 
@SamuelRicardoDS 
@brunomed 
@typejulio 
@lelamo2002 
@gustavokenzo1

**Comment by gustavokenzo1** [comment]
Sugestão: Caronas

Aplicação que permite que alunos, vans, etc, consigam se conectar e colaborar entre si para diminuir dificuldades e custos de locomoção até a FGA. Quem tiver carro poderá oferecer caronas gratuitas ou dividir custos de gasolina, e teria uma integração com a API do Google Maps para cálculo de rotas e desvios para pontos de encontro. Idéias: número de acentos vazios, quais dias da semana e quais horários a pessoa que está dando carona saíria e voltaria para casa, API de pagamentos para intermediar e garantir segurança para quem está oferecendo a carona...

**Comment by Bruno-Felix** [comment]
> Sugestão: Caronas
> 
> Aplicação que permite que alunos, vans, etc, consigam se conectar e colaborar entre si para diminuir dificuldades e custos de locomoção até a FGA. Quem tiver carro poderá oferecer caronas gratuitas ou dividir custos de gasolina, e teria uma integração com a API do Google Maps para cálculo de rotas e desvios para pontos de encontro. Idéias: número de acentos vazios, quais dias da semana e quais horários a pessoa que está dando carona saíria e voltaria para casa, API de pagamentos para intermediar e garantir segurança para quem está oferecendo a carona...

Excelente Sugestão de tema, Gustavo.
Só se atentem com o ponto de conexão com APIs externas. Isso aumenta o escopo do projeto. Considerando o tempo da disciplina e as prioridades de entrega tem que ter atenção envolta disso, ok?!

Bom trabalho!!
