### ISSUE TITLE
Documentação de comunidades de software livre

### ISSUE THREAD

**Issue by lelamo2002** [fga-eps-mds/2022-2-Vambora#26]
# Documentação de comunidades de software livre

## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Readme | Arquivo criado |
|   02   | codigo de conduta  | Arquivo criado |
|   03   | licença | Arquivo criado |
|   04   | guia de contribuição | Arquivo criado |
|   05   | template de issues | Arquivo criado |
|   06   | template de pull requests | Arquivo criado |

- [x] Tarefa 01
- [x] Tarefa 02
- [x] Tarefa 03
- [x] Tarefa 04
- [x] Tarefa 05
- [x] Tarefa 06

## Responsáveis

| Assignees  |
| :--------: |
| @lelamo2002  |
| @typejulio  |

**Comment by julio-dourado** [comment]
Aprovei Template de Issue e codigo de conduta.
