### ISSUE TITLE
Back-end: CRUD de Rota

### ISSUE THREAD

**Issue by julio-dourado** [fga-eps-mds/2022-2-Vambora#31]
# Back-end: CRUD de Rota
## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Dividir tarefas entre a equipe | Divisão revisada |
|   02   |  Definir horário de pareamentos | Horários definidos |
|   03   | configurar e padronizar ambiente de desenvolvimento dos membros | Todos os membros com ambientes Node.js e Docker |
|   04   | Rota GET | Teste da rota |
|   05   | Rota POST | Teste da rota |
|   06   | Rota PATCH | Teste da rota |
|   07   | Rota DELETE | Teste da rota |

- [x] Tarefa 01
- [x] Tarefa 02
- [x] Tarefa 03
- [x] Tarefa 04
- [x] Tarefa 05
- [x] Tarefa 06
- [x] Tarefa 07

**Comment by SamuelRicardoDS** [comment]
tarefas de 01 até 05 efetuadas com sucesso e testadas.

**Comment by brunomed** [comment]
CRUD finalizado com o DELETE
