### ISSUE TITLE
Criar fluxos de CI/CD

### ISSUE THREAD

**Issue by gustavokenzo1** [fga-eps-mds/2022-2-Vambora#34]
Pesquisar e implementar os fluxos de CI (Continuous Integration) e CD (Continuous Delivery)

**Comment by lelamo2002** [comment]
# Passos para concluir a issue:

- [x] Criar job na workflow para testar se o código está seguindo a lintagem e passa nos testes unitários
- [x] Criar conta na aws
- [x] Criar script para buildar a aplicação
- [ ] Criar job na workflow para testar se o código é buildado corretamente
- [ ] Criar a pipeline de CD
