### ISSUE TITLE
Sprint Planning

### ISSUE THREAD

**Issue by SamuelRicardoDS** [fga-eps-mds/2022-2-Vambora#7]
# Sprint Planning

## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | definição de carga horaria | reunião para idealização de tempo a ser trabalhado |
|   02   | adaptando requisitos às sprints | convertendo fluxo da aplicação e seus requisitos em sprints |
|   03   | documentação das sprints | revisão das sprints criadas e sua conversão em documentação |

- [x] Tarefa 01
- [x] Tarefa 02
- [ ] Tarefa 03

## Responsáveis

| Assignees  |
| :--------: |
| @SamuelRicardoDS  |
| @gustavokenzo1 |
| @typejulio |

**Comment by julio-dourado** [comment]
Sobre a definição da carga horária: a professora pediu 4 horas semanais fora o horário de aula para o projeto, acho um tempo curto mas possível.

Sobre adaptar requisitos às sprints: cada Sprint seria uma Feature, temos 6 no momento, totalizando 6 semanas para entregarmos em tese, mas tem sprints que necessitam de mais tempo.

Sobre documentação das Sprints: podemos seguir o exemplo da Acacia, eles utilizaram os tópicos: Planning, Período, Objetivo, Issues, Retrospectiva, Pontos positivos, negativos e etc, podemos definir alguém para me ajudar nessa parte. Oque acham ?

**Comment by julio-dourado** [comment]
No dia 13/12/2022 foi feita a Pull Request com todas as nossas praticas ágeis e cronograma das Sprints.
