### ISSUE TITLE
Adicionar Epic, Feature e US ao README

### ISSUE THREAD

**Issue by julio-dourado** [fga-eps-mds/2022-2-Vambora#8]
# Adicionar Epic, Feature e User Stories ao README.md

## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Passar a Epic, Feature e User Stories criadas no Miro para o README.md  | Revisão e validação do Product Owner|

- [x] Adicionar Epic, Feature e User Stories para README.md 
- [x] Revisar README.md

## Responsáveis

| @typejulio |
| @gustavokenzo1 |

**Comment by gustavokenzo1** [comment]
Vou marcar como concluída pq já dá uma boa ideia básica, talvez a gente altere alguma coisa no futuro, mas não tem tanto problema. Acho que o ideal seria passar do README pro GitHub Pages quando ele tiver mais bem estruturado...
